version:  "3.7"
services:
  db:
    container_name: mysql57
    image: mysql:5.7
    restart: on-failure
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblys
    ports:
      - "3307:3306"