version:  "3.7"
services:
  db:
    container_name: mysql56
    image: mysql:5.6
    restart: on-failure
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblys
    ports:
      - "3306:3306"